spring:
  mail:
    host: smtp.gmail.com
    username: iambabaprince@gmail.com
    password: xeriqttkibczpwdw
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true