spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowedHeaders:
              - Authorization
              - Content-Type
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allow-credentials: true